# Generated by Django 5.1.6 on 2025-02-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jorgeluisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosExternos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'datos_externos',
            },
        ),
    ]
