# Generated by Django 5.1.6 on 2025-02-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jorgeluisapp', '0002_datosexternos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatosExternos',
            new_name='DatosExternosjuan',
        ),
        migrations.AlterModelTable(
            name='datosexternosjuan',
            table='datos_externosjuan',
        ),
    ]
