# Generated by Django 5.1.6 on 2025-02-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jorgeluisapp', '0003_rename_datosexternos_datosexternosjuan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosExternoscris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
                ('stock', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'PRODUCTOS_CRISTIAN',
            },
        ),
    ]
