# Generated by Django 5.1.6 on 2025-02-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jorgeluisapp', '0004_datosexternoscris'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosExternoscamilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('horario', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Materias_camilo',
            },
        ),
    ]
