# Generated by Django 5.1.6 on 2025-02-23 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jorgeluisapp', '0005_datosexternoscamilo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosexternoscamilo',
            old_name='instructor',
            new_name='materia',
        ),
        migrations.RenameField(
            model_name='datosexternoscamilo',
            old_name='nombre',
            new_name='profesor',
        ),
    ]
