# Generated by Django 5.1.6 on 2025-02-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jorgeluisapp', '0006_rename_instructor_datosexternoscamilo_materia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoriteLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meteorite_id', models.IntegerField(unique=True)),
                ('nametype', models.CharField(max_length=50)),
                ('recclass', models.CharField(max_length=50)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('fall', models.CharField(max_length=10)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('reclat', models.FloatField(blank=True, null=True)),
                ('reclong', models.FloatField(blank=True, null=True)),
                ('geolocation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
