# Generated by Django 5.1.6 on 2025-02-25 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jorgeluisapp', '0007_meteoritelanding'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meteoritelanding',
            table='meteoro',
        ),
    ]
