# Generated by Django 5.1.6 on 2025-02-25 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jorgeluisapp', '0008_alter_meteoritelanding_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meteoritelanding',
            table=None,
        ),
    ]
