# Generated by Django 5.1.6 on 2025-03-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jorgeluisapp', '0010_remove_meteoritelanding_fall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('gps_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_id', models.CharField(blank=True, max_length=50, null=True)),
                ('market_regular', models.CharField(blank=True, max_length=20, null=True)),
                ('booking_id_date', models.DateTimeField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=20, null=True)),
                ('origin_location', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_location', models.CharField(blank=True, max_length=255, null=True)),
                ('org_lat_lon', models.CharField(blank=True, max_length=50, null=True)),
                ('des_lat_lon', models.CharField(blank=True, max_length=50, null=True)),
                ('data_ping_time', models.DateTimeField(blank=True, null=True)),
                ('planned_eta', models.DateTimeField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_location_actual', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_eta', models.DateTimeField(blank=True, null=True)),
                ('curr_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('curr_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('ontime', models.BooleanField(default=False)),
                ('delay', models.IntegerField(blank=True, null=True)),
                ('origin_location_code', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_location_code', models.CharField(blank=True, max_length=50, null=True)),
                ('trip_start_date', models.DateTimeField(blank=True, null=True)),
                ('trip_end_date', models.DateTimeField(blank=True, null=True)),
                ('transportation_distance_in_km', models.IntegerField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('minimum_kms_to_be_covered_in_a_day', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name_code', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_id', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier_name_code', models.CharField(blank=True, max_length=255, null=True)),
                ('material_shipped', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'trip_data',
            },
        ),
    ]
