# Generated by Django 5.1.6 on 2025-03-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jorgeluisapp', '0011_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='delay',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
