# Generated by Django 5.1.6 on 2025-03-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jorgeluisapp', '0012_alter_trip_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=50)),
                ('proveedor', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('rango_peso_envio', models.CharField(max_length=50)),
                ('ambito', models.CharField(max_length=50)),
                ('tipo_envio', models.CharField(max_length=50)),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('ingresos', models.CharField(max_length=150)),
                ('numero_total_envios', models.IntegerField()),
            ],
            options={
                'db_table': 'envios',
            },
        ),
    ]
